const express = require('express');
const bodyParser = require('body-parser');
const cors = require('cors');
const { sequelize } = require('./models');  // Automatically generated by Sequelize

const app = express();
app.use(cors());
app.use(bodyParser.json());

// Import routes
require('./routes')(app);

// Sync database and start server
sequelize.sync({ force: false }).then(() => {
  app.listen(3000, () => console.log('Server running on http://localhost:3000'));
});
